### ISSUE TITLE
Joystick controls do not work when resuming from sleep

### ISSUE THREAD

**Issue by ConorMcCaffrey** [UAX-Technologies/DeckRC#15]
**Describe the bug**
The joystick controls do not work after resuming from sleep

**To Reproduce**
Power on system
enable sc controller
open qgc
put device to sleep
wake device
controls will be unresponsive

**Comment by ConorMcCaffrey** [comment]
Ran the sc-co troller daemon in debug mode, along side opening the app image as normal.
#sc-controller.appimage daemon debug

Found these errors when resuming from sleep:

D:deck:Got SteamDeck with serial 3:3 D:USB:USB device added: 28de:1205 D:SCCDaemon:Assigned default_mapper to <Deck deck3:3> D:SCCDaemon:Controller added: <Deck deck3:3> D OSD:DaemonCtrl:Connected to daemon, version 0.4.8 D OSD:Daemonctrl:Daemon reported profile change for deck3:3: /home/deck/config/scc/profiles/Desktop.sccprofile D OSD:DaemonCtrl:Daemon is ready. I:SCCDaemon:Registered scc-osd-daemon I OSD:osd.daemon:Sucessfully registered as scc-osd-daemon Traceback (most recent call last): File "_ctypes/callbacks.c", line 315, in 'calling callback function File "/tmp/.mount_sc-conDRet61/usr/lib/python2.7/site-packages/scc/lib/usb1.py", line 322, in callbackirapper callback(self) File "/tmp/.mount_sc-conDRet61/usr/lib/python2.7/site-packages/scc/drivers/usb.py", line 47, in callback wrapper transfer.submit() File "/tmp/.mount_sc-conDRet61/usr/lib/python2.7/site-packages/scc/lib/usb1.py", line 722, in submtt raiseUSBError(result) File "/tmp/.mount_sc-conDRet61/usr/lib/python2.7/site-packages/scc/lib/usb1.py", line 117, in raiseuSBError raise STATUS_TO_EXCEPTION_DICT.get(value, USBError)(value) scc.lib.usb1.USBErrorIO: LIBUSP FRROR_IO [-1]

**Comment by ConorMcCaffrey** [comment]
If the daemon is stopped and restarted the controls work again. Creating a script that executes 
$ /home/deck/Desktop/sc-controller.AppImage daemon restart
Might work. When the command is executed manually it does recover the controls after standby. Calling it from a user systemd service is not yet working.

There is an alternative path. If you de-select and re-select the enable emulation option in sc-controller after resuming from suspend, then the controls come back. It might be possible to create a script that changes that setting and back.

**Comment by ConorMcCaffrey** [comment]
It is related to this [issue](https://github.com/kozec/sc-controller/issues/696)

**Comment by ConorMcCaffrey** [comment]
I was trying to use a systemd service to restart the daemon but hit a few snags. The suspend.target is only available to the root systemd. The user mode systemd is needed to call the restart daemon because the process and config is all under that user.

I think the easiest option (short of actually fixing the problem) will be to use a system service that calls the user service.

**Comment by ConorMcCaffrey** [comment]
Interesting finding that newer version of SteamOS show the controller as "Steam Deck" and give basic HID outputs without SC controller running. This also survives standby and resume. The trackpads do not have any function in this mode.

I am going to see if SC-controller and the built in controls can run at the same time. That way QGC gets the good "Steam Deck" controls. And sc-controller allows us to enable additional functions for the trackpads and such, which are not flight critical.

**Comment by ConorMcCaffrey** [comment]
Interesting program here  Have not tested it.
https://codeberg.org/OpenSD/opensd
